/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FxSalesRouteImport } from './routes/fx-sales'
import { Route as FxRiskRouteImport } from './routes/fx-risk'
import { Route as CurrencyBalanceRouteImport } from './routes/currency-balance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FxSalesRoute = FxSalesRouteImport.update({
  id: '/fx-sales',
  path: '/fx-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const FxRiskRoute = FxRiskRouteImport.update({
  id: '/fx-risk',
  path: '/fx-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyBalanceRoute = CurrencyBalanceRouteImport.update({
  id: '/currency-balance',
  path: '/currency-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/currency-balance': typeof CurrencyBalanceRoute
  '/fx-risk': typeof FxRiskRoute
  '/fx-sales': typeof FxSalesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/currency-balance': typeof CurrencyBalanceRoute
  '/fx-risk': typeof FxRiskRoute
  '/fx-sales': typeof FxSalesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/currency-balance': typeof CurrencyBalanceRoute
  '/fx-risk': typeof FxRiskRoute
  '/fx-sales': typeof FxSalesRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/currency-balance'
    | '/fx-risk'
    | '/fx-sales'
    | '/journal'
    | '/login'
    | '/contacts/$contactId'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/currency-balance'
    | '/fx-risk'
    | '/fx-sales'
    | '/journal'
    | '/login'
    | '/contacts/$contactId'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/currency-balance'
    | '/fx-risk'
    | '/fx-sales'
    | '/journal'
    | '/login'
    | '/contacts/$contactId'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrencyBalanceRoute: typeof CurrencyBalanceRoute
  FxRiskRoute: typeof FxRiskRoute
  FxSalesRoute: typeof FxSalesRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx-sales': {
      id: '/fx-sales'
      path: '/fx-sales'
      fullPath: '/fx-sales'
      preLoaderRoute: typeof FxSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx-risk': {
      id: '/fx-risk'
      path: '/fx-risk'
      fullPath: '/fx-risk'
      preLoaderRoute: typeof FxRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-balance': {
      id: '/currency-balance'
      path: '/currency-balance'
      fullPath: '/currency-balance'
      preLoaderRoute: typeof CurrencyBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrencyBalanceRoute: CurrencyBalanceRoute,
  FxRiskRoute: FxRiskRoute,
  FxSalesRoute: FxSalesRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
